#!/usr/local/bin/lua

package.preload['files_tree'] =
  function(...)
    require('workshop.base')
    local files_to_stream
    do
      local file_to_str = request('!.convert.file_to_str')
      local encode_itness = request('!.concepts.codec_itness.compile')
      files_to_stream =
        function(FileNames, Output)
          for _, file_name in ipairs(FileNames) do
            encode_itness({ file_name, file_to_str(file_name) }, Output)
          end
        end
    end
    local files_from_stream
    do
      local decode_itness = request('!.concepts.codec_itness.parse')
      local rebase_to = request('!.concepts.path_name.rebase_to')
      local file_from_str = request('!.convert.file_from_str')
      files_from_stream =
        function(Input, output_dir)
          while true do
            local FileRec = decode_itness(Input)
            if not is_table(FileRec) then
              break
            end
            local name = FileRec[1]
            local data = FileRec[2]
            name = rebase_to(output_dir, name)
            file_from_str(name, data)
          end
        end
    end
    local print_help
    do
      local help_text =
        [[
Codec between several files and one file

Usage: <action> <input_name> <output_name>

  <action> -- what to do. One of:

    export -- combine files
      from <input_name> directory to <output_name> file

    import -- decombine files
      from <input_name> file to <output_name> directory

-- Martin, 2026-10
]]
      print_help =
        function()
          io.stdout:write(help_text)
        end
    end
    local action = arg[1]
    local input_name = arg[2]
    local output_name = arg[3]
    if not (action and input_name and output_name) then
      print_help()
      return
    end
    if (action == 'export') then
      local input_dir = input_name
      local output_file_name = output_name
      local FilesList
      do
        local get_files_list =
          request('!.file_system.directory.get_total_files_list')
        FilesList = get_files_list(input_dir)
      end
      local Output
      do
        local OutputFile = request('!.concepts.StreamIo.Output.File')
        Output = OutputFile.create(output_file_name)
      end
      Output:Open()
      files_to_stream(FilesList, Output)
      Output:Close()
    elseif (action == 'import') then
      local input_file_name = input_name
      local output_dir = output_name
      local Input
      do
        local InputFile = request('!.concepts.StreamIo.Input.File')
        Input = InputFile.create(input_file_name)
      end
      Input:Open()
      files_from_stream(Input, output_dir)
      Input:Close()
    end
  end
package.preload['workshop.base'] =
  function(...)
    local set_base_prefix
    local split_name
    local get_base_prefix
    local request
    local stack_init
    local stack_add
    local stack_remove
    do
      local str_match = string.match
      local str_find = string.find
      local str_sub = string.sub
      local tbl_pack = table.pack
      local tbl_unpack = table.unpack
      local require = require
      local empty = ''
      local stack_get
      do
        local Names
        local depth
        stack_init =
          function()
            Names = { }
            depth = 1
          end
        stack_get =
          function()
            return Names[depth]
          end
        stack_add =
          function(prefix, name)
            depth = depth + 1
            Names[depth] = { prefix = prefix, name = name }
          end
        stack_remove =
          function()
            depth = depth - 1
          end
      end
      local get_caller_prefix =
        function()
          local NameRec = stack_get()
          if not NameRec then
            return empty
          end
          return NameRec.prefix
        end
      do
        local prefix_name_capture = '^(.+%.)([^%.]+)$'
        split_name =
          function(qualified_name)
            local prefix, name =
              str_match(qualified_name, prefix_name_capture)
            if not prefix then
              prefix = empty
              if str_find(qualified_name, '%.') then
                name = empty
              else
                name = qualified_name
              end
            end
            return prefix, name
          end
      end
      local apply_rel_prefix
      do
        local uplevel_capture = '(.+%.)[^%.]-%.$'
        apply_rel_prefix =
          function(base_prefix, rel_prefix)
            while (str_sub(rel_prefix, 1, 2) == '^.') do
              if (base_prefix == empty) then
                error("Link is outside of caller's prefix.")
              end
              base_prefix =
                str_match(base_prefix, uplevel_capture) or empty
              rel_prefix = str_sub(rel_prefix, 3)
            end
            return base_prefix .. rel_prefix
          end
      end
      do
        local base_prefix
        set_base_prefix =
          function(arg_base_prefix)
            base_prefix = arg_base_prefix
          end
        get_base_prefix =
          function()
            return base_prefix
          end
      end
      local get_require_name =
        function(qualified_name)
          local caller_prefix
          local is_absolute_name =
            (str_sub(qualified_name, 1, 2) == '!.')
          if is_absolute_name then
            qualified_name = str_sub(qualified_name, 3)
            caller_prefix = get_base_prefix()
          else
            caller_prefix = get_caller_prefix()
          end
          local prefix, name = split_name(qualified_name)
          prefix = apply_rel_prefix(caller_prefix, prefix)
          return prefix .. name
        end
      request =
        function(qualified_name)
          local require_name = get_require_name(qualified_name)
          stack_add(split_name(require_name))
          local Results = tbl_pack(require(require_name))
          stack_remove()
          return tbl_unpack(Results)
        end
    end
    do
      local our_require_name = (...)
      set_base_prefix(split_name(our_require_name))
      _G.request = request
      _G.get_base_prefix = get_base_prefix
      stack_init()
      stack_add(empty, our_require_name)
      request('!.system.install_is_functions')()
      request('!.system.install_assert_functions')()
      _G.new = request('!.table.new')
      stack_remove()
    end
  end
package.preload['workshop.concepts.Indent'] =
  function(...)
    local get_indent_chunk =
      function(Me)
        return Me[1]
      end
    local set_indent_chunk =
      function(Me, str)
        Me[1] = str
      end
    local get_indent_level =
      function(Me)
        return Me[2]:GetValue()
      end
    local set_indent_level =
      function(Me, level)
        Me[2]:SetValue(level)
      end
    local to_string
    do
      local str_rep = string.rep
      to_string =
        function(Me)
          return str_rep(Me[1], Me[2]:GetValue())
        end
    end
    local inc =
      function(Me)
        set_indent_level(Me, get_indent_level(Me) + 1)
      end
    local dec =
      function(Me)
        set_indent_level(Me, get_indent_level(Me) - 1)
      end
    local Interface
    local create
    do
      local RangePointClass = request('!.concepts.RangePoint')
      local default_indent_chunk = '  '
      local default_min_indent = 0
      local default_max_indent = 60
      local attach_methods = request('!.table.attach_methods')
      create =
        function(OptArg)
          local min_indent = default_min_indent
          local max_indent = default_max_indent
          if OptArg then
            min_indent = OptArg.min or min_indent
            max_indent = OptArg.max or max_indent
          end
          local RangePoint = RangePointClass.create()
          RangePoint:SetMinValue(min_indent)
          RangePoint:SetMaxValue(max_indent)
          RangePoint:SetValue(min_indent)
          local Core = { default_indent_chunk, RangePoint }
          attach_methods(Core, Interface)
          return Core
        end
    end
    Interface =
      {
        create = create,
        GetIndentChunk = get_indent_chunk,
        SetIndentChunk = set_indent_chunk,
        GetIndentLevel = get_indent_level,
        SetIndentLevel = set_indent_level,
        ToString = to_string,
        Inc = inc,
        Dec = dec,
      }
    return Interface
  end
package.preload['workshop.concepts.RangePoint'] =
  function(...)
    local get_min_value =
      function(Me)
        return Me[2]
      end
    local set_min_value =
      function(Me, val)
        Me[2] = val
      end
    local get_max_value =
      function(Me)
        return Me[3]
      end
    local set_max_value =
      function(Me, val)
        Me[3] = val
      end
    local get_value
    local set_value
    do
      local min = math.min
      local max = math.max
      get_value =
        function(Me)
          return min(max(Me[1], Me[2]), Me[3])
        end
      set_value =
        function(Me, value)
          Me[1] = min(max(value, Me[2]), Me[3])
        end
    end
    local Interface
    local create
    do
      local attach_methods = request('!.table.attach_methods')
      create =
        function()
          local Core = { 0, 0, 1 }
          attach_methods(Core, Interface)
          return Core
        end
    end
    Interface =
      {
        create = create,
        GetMinValue = get_min_value,
        SetMinValue = set_min_value,
        GetMaxValue = get_max_value,
        SetMaxValue = set_max_value,
        GetValue = get_value,
        SetValue = set_value,
      }
    return Interface
  end
package.preload['workshop.concepts.ShellCommand'] =
  function(...)
    local ToString
    do
      local quote = request('!.concepts.shell.quote')
      local add_to_list = request('!.concepts.list.add_item')
      local glue_words = request('!.concepts.words.to_string')
      ToString =
        function(Me)
          local command = Me[1]
          local Args = Me[2]
          local Words = { }
          add_to_list(Words, quote(command))
          for _, arg in ipairs(Args) do
            add_to_list(Words, quote(arg))
          end
          return glue_words(Words)
        end
    end
    local Execute
    do
      local execute_shell_command = request('!.concepts.shell.execute')
      Execute =
        function(Me)
          return execute_shell_command(Me:ToString())
        end
    end
    local Interface
    do
      local create
      do
        local create_instance = request('!.table.create_instance')
        create =
          function(Core)
            do
              assert_table(Core)
              assert(#Core == 2)
              local command = Core[1]
              local Args = Core[2]
              assert_string(command)
              assert_table(Args)
              for _, arg in ipairs(Args) do
                assert_string(arg)
              end
            end
            return create_instance(Core, Interface)
          end
      end
      Interface =
        { create = create, ToString = ToString, Execute = Execute }
    end
    return Interface
  end
package.preload['workshop.concepts.Ascii.Chars'] =
  function(...)
    local Chars
    do
      local Codes = request('Codes')
      local str_char = string.char
      Chars = { }
      for name, code in pairs(Codes) do
        Chars[name] = str_char(code)
      end
    end
    return Chars
  end
package.preload['workshop.concepts.Ascii.Codes'] =
  function(...)
    return
      {
        bell = 7,
        backspace = 8,
        tab = 9,
        newline = 10,
        vertical_tab = 11,
        form_feed = 12,
        carriage_return = 13,
        space = 32,
        delete = 127,
        plus = 43,
        minus = 45,
        asterisk = 42,
        slash = 47,
        less_than = 60,
        equals = 61,
        greater_than = 62,
        dot = 46,
        comma = 44,
        colon = 58,
        semicolon = 59,
        single_quote = 39,
        double_quote = 34,
        backtick = 96,
        backslash = 92,
        number_sign = 35,
        question_mark = 63,
        bang = 33,
        percent = 37,
        ampersand = 38,
        dollar_sign = 36,
        at_sign = 64,
        caret = 94,
        underscore = 95,
        pipe = 124,
        tilde = 126,
        opening_paren = 40,
        closing_paren = 41,
        opening_bracket = 91,
        closing_bracket = 93,
        opening_brace = 123,
        closing_brace = 125,
      }
  end
package.preload['workshop.concepts.StreamIo.Input.File'] =
  function(...)
    local open
    do
      local open_file_for_reading =
        request('!.file_system.file.open_for_reading')
      open =
        function(Me)
          Me[2] = open_file_for_reading(Me[1])
        end
    end
    local close
    do
      local close_file = request('!.file_system.file.close')
      close =
        function(Me)
          close_file(Me[2])
        end
    end
    local read
    do
      local is_natural = request('!.number.is_natural')
      read =
        function(Me, num_bytes)
          assert(is_natural(num_bytes))
          local data_str = Me[2]:read(num_bytes)
          if is_nil(data_str) then
            data_str = ''
          end
          return data_str
        end
    end
    local Interface
    local create
    do
      local attach_methods = request('!.table.attach_methods')
      create =
        function(pathname)
          assert_string(pathname)
          local Me = { pathname, 0 }
          attach_methods(Me, Interface)
          return Me
        end
    end
    Interface =
      { create = create, Open = open, Close = close, Read = read }
    return Interface
  end
package.preload['workshop.concepts.StreamIo.Output.File'] =
  function(...)
    local open
    do
      local create_file = request('!.file_system.file.create')
      local open_for_writing =
        request('!.file_system.file.open_for_writing')
      open =
        function(Me)
          create_file(Me[1], '')
          Me[2] = open_for_writing(Me[1])
        end
    end
    local close
    do
      local close_file = request('!.file_system.file.close')
      close =
        function(Me)
          close_file(Me[2])
        end
    end
    local write =
      function(Me, data_str)
        assert_string(data_str)
        Me[2]:write(data_str)
      end
    local Interface
    local create
    do
      local attach_methods = request('!.table.attach_methods')
      create =
        function(pathname)
          assert_string(pathname)
          local Me = { pathname, 0 }
          attach_methods(Me, Interface)
          return Me
        end
    end
    Interface =
      { create = create, Open = open, Close = close, Write = write }
    return Interface
  end
package.preload['workshop.concepts.codec_itness.compile'] =
  function(...)
    local DataWriter = request('compile.DataWriter.Interface')
    local DelimitersWriter =
      request('compile.DelimitersWriter.Interface')
    local Syntax = request('common.Syntax')
    return
      function(Node, Output)
        local DataWriter = new(DataWriter)
        local DelimitersWriter = new(DelimitersWriter)
        local compile
        compile =
          function(Node)
            if is_string(Node) then
              DelimitersWriter:HandleEvent('write_string')
              DataWriter:WriteLeaf(Node)
            elseif is_table(Node) then
              DelimitersWriter:HandleEvent('start_list')
              DataWriter:StartList()
              for _, Node in ipairs(Node) do
                compile(Node)
              end
              DelimitersWriter:HandleEvent('end_list')
              DataWriter:EndList()
            end
          end
        DataWriter.Output = Output
        DataWriter.Syntax = Syntax
        DataWriter:Init()
        DelimitersWriter.Output = Output
        DelimitersWriter.space_char = Syntax.delimiters_space_char
        DelimitersWriter.newline_char = Syntax.delimiters_newline_char
        DelimitersWriter:Init()
        compile(Node)
        DelimitersWriter:HandleEvent('nothing')
      end
  end
package.preload['workshop.concepts.codec_itness.parse'] =
  function(...)
    local Syntax = request('common.Syntax')
    local read_token
    do
      local quote_open_char = Syntax.quote_open_char
      local quote_close_char = Syntax.quote_close_char
      local space_char = Syntax.delimiters_space_char
      local newline_char = Syntax.delimiters_newline_char
      read_token =
        function(Input)
          local token = ''
          local in_quotes = false
          while true do
            local char = Input:Read(1)
            if (char == '') then
              return token
            end
            if in_quotes then
              if (char == quote_close_char) then
                in_quotes = false
              else
                token = token .. char
              end
            else
              if (char == space_char) or (char == newline_char) then
                if (token ~= '') then
                  return token
                end
              elseif (char == quote_open_char) then
                in_quotes = true
              else
                token = token .. char
              end
            end
          end
        end
    end
    local parse
    do
      local group_open_char = Syntax.group_open_char
      local group_close_char = Syntax.group_close_char
      local add_to_list = request('!.concepts.list.add_item')
      parse =
        function(Input)
          while true do
            local token = read_token(Input)
            if (token == '') then
              return
            end
            if (token == group_open_char) then
              local Result = { }
              while true do
                local Node = parse(Input)
                if not Node then
                  break
                end
                add_to_list(Result, Node)
              end
              return Result
            elseif (token == group_close_char) then
              return
            else
              return token
            end
          end
        end
    end
    return parse
  end
package.preload['workshop.concepts.codec_itness.common.Syntax'] =
  function(...)
    local Syntax =
      {
        delimiters_space_char = ' ',
        delimiters_newline_char = '\n',
        quote_open_char = '[',
        quote_close_char = ']',
        group_open_char = '(',
        group_close_char = ')',
      }
    return Syntax
  end
package.preload[
  'workshop.concepts.codec_itness.compile.DataWriter.Interface'
] =
  function(...)
    local get_values = request('!.table.get_values')
    local map_values = request('!.table.map_values')
    local list_to_string = request('!.concepts.list.to_string')
    local lua_regexp_quote = request('!.lua.regexp.quote')
    local Interface =
      {
        Output = { },
        Syntax = { },
        Init =
          function(Me)
            local SyntaxList = get_values(Me.Syntax)
            Me.IsSyntaxChar_Map = map_values(SyntaxList)
            Me.syntax_chars_regexp =
              '[' .. lua_regexp_quote(list_to_string(SyntaxList)) .. ']'
          end,
        StartList =
          function(Me)
            Me.Output:Write(Me.Syntax.group_open_char)
          end,
        EndList =
          function(Me)
            Me.Output:Write(Me.Syntax.group_close_char)
          end,
        WriteLeaf = request('WriteLeaf'),
        IsSyntaxChar_Map = { },
        syntax_chars_regexp = '',
      }
    return Interface
  end
package.preload[
  'workshop.concepts.codec_itness.compile.DataWriter.WriteLeaf'
] =
  function(...)
    local WriteLeaf =
      function(Me, str)
        local quote_open_char = Me.Syntax.quote_open_char
        local quote_close_char = Me.Syntax.quote_close_char
        local IsSyntaxChar_Map = Me.IsSyntaxChar_Map
        local syntax_chars_regexp = Me.syntax_chars_regexp
        local in_quotes = false
        local encode_char =
          function(char)
            local Result = char
            if
              not in_quotes and
              (IsSyntaxChar_Map[char] and (char ~= quote_close_char))
            then
              Result = quote_open_char .. char
              in_quotes = true
            end
            if in_quotes and (char == quote_close_char) then
              Result = quote_close_char .. char
              in_quotes = false
            end
            return Result
          end
        local encoded_str =
          string.gsub(str, syntax_chars_regexp, encode_char)
        if in_quotes then
          encoded_str = encoded_str .. quote_close_char
          in_quotes = false
        end
        if (str == '') then
          encoded_str = quote_open_char .. quote_close_char
        end
        Me.Output:Write(encoded_str)
      end
    return WriteLeaf
  end
package.preload[
  'workshop.concepts.codec_itness.compile.DelimitersWriter.HandleEvent'
] =
  function(...)
    local Emit =
      function(Me, str)
        if (str == '') then
          return
        end
        Me.Output:Write(str)
        Me.is_on_empty_line = false
      end
    local EmitNewline =
      function(Me)
        if Me.is_on_empty_line then
          return
        end
        Emit(Me, Me.newline_char)
        Me.is_on_empty_line = true
      end
    local EmitIndent =
      function(Me)
        EmitNewline(Me)
        Emit(Me, Me.Indent:ToString())
      end
    local F_Empty =
      function(Me)
      end
    local F_Indent =
      function(Me)
        EmitIndent(Me)
      end
    local F_Space =
      function(Me)
        Emit(Me, Me.space_char)
      end
    local EventsToFunc =
      {
        ['nothing'] =
          {
            ['nothing'] = F_Empty,
            ['write_string'] = F_Empty,
            ['start_list'] = F_Empty,
            ['end_list'] = F_Empty,
          },
        ['write_string'] =
          {
            ['nothing'] = F_Empty,
            ['write_string'] = F_Space,
            ['start_list'] = F_Indent,
            ['end_list'] = F_Space,
          },
        ['start_list'] =
          {
            ['nothing'] = F_Empty,
            ['write_string'] = F_Space,
            ['start_list'] = F_Indent,
            ['end_list'] = F_Empty,
          },
        ['end_list'] =
          {
            ['nothing'] = F_Indent,
            ['write_string'] = F_Indent,
            ['start_list'] = F_Indent,
            ['end_list'] = F_Indent,
          },
      }
    local OnEvent =
      function(Me, cur_event)
        if (Me.prev_event ~= 'nothing') then
          Me.is_on_empty_line = false
        end
        if (cur_event == 'end_list') then
          Me.Indent:Dec()
        end
        local PaddingFunc = EventsToFunc[Me.prev_event][cur_event]
        PaddingFunc(Me)
        if (cur_event == 'start_list') then
          Me.Indent:Inc()
        end
        Me.prev_event = cur_event
      end
    return OnEvent
  end
package.preload[
  'workshop.concepts.codec_itness.compile.DelimitersWriter.Interface'
] =
  function(...)
    local IndentClass = request('!.concepts.Indent')
    local Interface =
      {
        Output = { },
        space_char = '',
        newline_char = '',
        Init =
          function(Me)
            Me.Indent = IndentClass.create()
            local space_char = Me.space_char
            local spaces_per_indent = 2
            local indent_chunk =
              string.rep(space_char, spaces_per_indent)
            Me.Indent:SetIndentChunk(indent_chunk)
            Me.prev_event = 'nothing'
            Me.is_on_empty_line = true
          end,
        HandleEvent = request('HandleEvent'),
        Indent = Indent,
        prev_event = '',
        is_on_empty_line = false,
      }
    return Interface
  end
package.preload['workshop.concepts.list.add_item'] =
  function(...)
    local tbl_insert = table.insert
    return
      function(OurList, item)
        tbl_insert(OurList, item)
      end
  end
package.preload['workshop.concepts.list.add_list'] =
  function(...)
    local tbl_move = table.move
    return
      function(OurList, AnotherList)
        assert(OurList ~= AnotherList)
        tbl_move(AnotherList, 1, #AnotherList, #OurList + 1, OurList)
      end
  end
package.preload['workshop.concepts.list.select_seg'] =
  function(...)
    local is_natural = request('!.number.is_natural')
    local tbl_move = table.move
    return
      function(List, start_idx, len)
        assert(is_natural(start_idx))
        assert(is_natural(len))
        local stop_idx = start_idx + len - 1
        local Result = { }
        tbl_move(List, start_idx, stop_idx, 1, Result)
        return Result
      end
  end
package.preload['workshop.concepts.list.to_string'] =
  function(...)
    local tbl_concat = table.concat
    return
      function(List, separator_str)
        assert_table(List)
        separator_str = separator_str or ''
        assert_string(separator_str)
        return tbl_concat(List, separator_str)
      end
  end
package.preload['workshop.concepts.lua.NumberTypeNames'] =
  function(...)
    return { 'integer', 'float' }
  end
package.preload['workshop.concepts.lua.TypeNames'] =
  function(...)
    return
      {
        'nil',
        'boolean',
        'number',
        'string',
        'function',
        'thread',
        'userdata',
        'table',
      }
  end
package.preload['workshop.concepts.path_name.Syntels'] =
  function(...)
    return { separator = '/', self_dir = '.', upper_dir = '..' }
  end
package.preload['workshop.concepts.path_name.add_separator'] =
  function(...)
    local sep = request('Syntels').separator
    local ends_with = request('!.string.ends_with')
    return
      function(str)
        if ends_with(str, sep) then
          return str
        end
        return str .. sep
      end
  end
package.preload['workshop.concepts.path_name.get_host_dir'] =
  function(...)
    local self_dir = request('Syntels').self_dir
    local is_directory = request('is_directory')
    local is_absolute = request('is_absolute')
    local select_seg = request('!.concepts.list.select_seg')
    local add_to_list = request('!.concepts.list.add_item')
    return
      function(Pathname)
        local HostDir
        local host_dir_end_idx
        if is_directory(Pathname) then
          host_dir_end_idx = #Pathname - 2
        else
          host_dir_end_idx = #Pathname - 1
        end
        if (host_dir_end_idx <= 0) then
          if is_absolute(Pathname) then
            HostDir = { '' }
          else
            HostDir = { self_dir }
          end
        else
          HostDir = select_seg(Pathname, 1, host_dir_end_idx)
        end
        add_to_list(HostDir, '')
        return HostDir
      end
  end
package.preload['workshop.concepts.path_name.get_host_dir_str'] =
  function(...)
    local pathname_from_str = request('pathname_from_str')
    local pathname_to_str = request('pathname_to_str')
    local get_host_dir = request('get_host_dir')
    return
      function(pathname)
        return
          pathname_to_str(get_host_dir(pathname_from_str(pathname)))
      end
  end
package.preload['workshop.concepts.path_name.is_absolute'] =
  function(...)
    return
      function(Pathname)
        return (Pathname[1] == '')
      end
  end
package.preload['workshop.concepts.path_name.is_directory'] =
  function(...)
    local self_dir
    local upper_dir
    do
      local Syntels = request('Syntels')
      self_dir = Syntels.self_dir
      upper_dir = Syntels.upper_dir
    end
    return
      function(Pathname)
        local last_node = Pathname[#Pathname]
        return
          (last_node == '') or
          (last_node == self_dir) or
          (last_node == upper_dir)
      end
  end
package.preload['workshop.concepts.path_name.normalize'] =
  function(...)
    local pathname_from_str = request('pathname_from_str')
    local pathname_to_str = request('pathname_to_str')
    return
      function(path_name)
        return pathname_to_str(pathname_from_str(path_name))
      end
  end
package.preload['workshop.concepts.path_name.pathname_from_str'] =
  function(...)
    local split_string = request('!.string.split')
    local check_is_absolute = request('is_absolute')
    local check_is_directory = request('is_directory')
    local add_to_list = request('!.concepts.list.add_item')
    local add_list = request('!.concepts.list.add_list')
    local empty = ''
    local self_dir
    local sep
    do
      local Syntels = request('Syntels')
      self_dir = Syntels.self_dir
      sep = Syntels.separator
    end
    return
      function(path_name)
        assert_string(path_name)
        if (path_name == empty) then
          error('Empty pathname.')
        end
        local is_absolute
        local is_directory
        local Names = { }
        do
          local Segments = split_string(path_name .. sep, sep)
          is_absolute = check_is_absolute(Segments)
          is_directory = check_is_directory(Segments)
          for _, segment in ipairs(Segments) do
            if (segment ~= empty) and (segment ~= self_dir) then
              add_to_list(Names, segment)
            end
          end
        end
        if (#Names == 0) and not is_absolute then
          add_to_list(Names, self_dir)
        end
        do
          local Result = { }
          if is_absolute then
            add_to_list(Result, empty)
          end
          add_list(Result, Names)
          if is_directory then
            add_to_list(Result, empty)
          end
          return Result
        end
      end
  end
package.preload['workshop.concepts.path_name.pathname_to_str'] =
  function(...)
    local sep = request('Syntels').separator
    local clean_pathname
    do
      local clean_name
      do
        local ends_with = request('!.string.ends_with')
        local str_sub = string.sub
        clean_name =
          function(name)
            local sep_len = #sep
            while ends_with(name, sep) do
              name = str_sub(name, 1, -(sep_len + 1))
            end
            return name
          end
      end
      local add_to_list = request('!.concepts.list.add_item')
      clean_pathname =
        function(Pathname)
          local Result = { }
          for _, name in ipairs(Pathname) do
            add_to_list(Result, clean_name(name))
          end
          return Result
        end
    end
    local list_to_str = request('!.concepts.list.to_string')
    return
      function(Pathname)
        return list_to_str(clean_pathname(Pathname), sep)
      end
  end
package.preload['workshop.concepts.path_name.rebase_to'] =
  function(...)
    local pathname_from_str = request('pathname_from_str')
    local tbl_remove = table.remove
    local RangePoint = request('!.concepts.RangePoint')
    local upper_dir = request('Syntels').upper_dir
    local add_list = request('!.concepts.list.add_list')
    local pathname_to_str = request('pathname_to_str')
    return
      function(dest_dir, pathname)
        assert_string(dest_dir)
        assert_string(pathname)
        local DestNames = pathname_from_str(dest_dir)
        local MovedNames = pathname_from_str(pathname)
        if (DestNames[#DestNames] == '') then
          tbl_remove(DestNames, #DestNames)
        end
        if (MovedNames[1] == '') then
          tbl_remove(MovedNames, 1)
        end
        do
          local Cursor = RangePoint.create()
          Cursor:SetMinValue(1)
          Cursor:SetMaxValue(#MovedNames + 1)
          Cursor:SetValue(1)
          for name_index = 1, #MovedNames do
            local cursor_pos = Cursor:GetValue()
            if (MovedNames[name_index] == upper_dir) then
              Cursor:SetValue(cursor_pos - 1)
            else
              MovedNames[cursor_pos] = MovedNames[name_index]
              Cursor:SetValue(cursor_pos + 1)
            end
          end
          for name_index = Cursor:GetValue(), #MovedNames do
            MovedNames[name_index] = nil
          end
        end
        local Result = { }
        add_list(Result, DestNames)
        add_list(Result, MovedNames)
        return pathname_to_str(Result)
      end
  end
package.preload['workshop.concepts.shell.execute'] =
  function(...)
    local get_is_aborted =
      function(result_type_code)
        if (result_type_code == 'signal') then
          return true
        elseif (result_type_code == 'exit') then
          return false
        else
          error('Unknown termination status.')
        end
      end
    local os_tmpname = os.tmpname
    local os_execute = os.execute
    local file_to_str = request('!.convert.file_to_str')
    local os_remove = os.remove
    return
      function(command)
        local output_filename = os_tmpname()
        local error_filename = os_tmpname()
        local shell_command =
          command ..
          ' ' ..
          '1>' ..
          output_filename ..
          ' ' ..
          '2>' ..
          error_filename
        local _, result_type_code, result_code =
          os_execute(shell_command)
        local Result =
          {
            result_code = result_code,
            is_aborted = get_is_aborted(result_type_code),
            output = file_to_str(output_filename),
            error = file_to_str(error_filename),
          }
        os_remove(output_filename)
        os_remove(error_filename)
        return (Result.result_code == 0), Result
      end
  end
package.preload['workshop.concepts.shell.quote'] =
  function(...)
    local empty = ''
    local single_quote
    local backslash
    do
      local Ascii = request('!.concepts.Ascii.Chars')
      single_quote = Ascii.single_quote
      backslash = Ascii.backslash
    end
    local list_to_str = request('!.concepts.list.to_string')
    local str_find = string.find
    local needs_quoting
    do
      local special_chars_regexp
      local starts_with_comment_regexp
      do
        local quote_regexp = request('!.lua.regexp.quote')
        do
          local SpecialChars = request('quote.SpecialChars')
          local special_chars_str = list_to_str(SpecialChars)
          special_chars_regexp =
            '[' .. quote_regexp(special_chars_str) .. ']'
        end
        do
          local SpaceChars = request('quote.SpaceChars')
          local space_chars_str = list_to_str(SpaceChars)
          local space_chars_regexp =
            '[' .. quote_regexp(space_chars_str) .. ']'
          local comment_char = '#'
          starts_with_comment_regexp =
            '^' .. space_chars_regexp .. '+' .. comment_char
        end
      end
      needs_quoting =
        function(str)
          return
            (str == empty) or
            not is_nil(str_find(str, special_chars_regexp)) or
            not is_nil(str_find(str, starts_with_comment_regexp))
        end
    end
    local split_string = request('!.string.split')
    local add_to_list = request('!.concepts.list.add_item')
    local quote
    quote =
      function(str)
        assert_string(str)
        if not needs_quoting(str) then
          return str
        end
        if not str_find(str, single_quote) then
          return single_quote .. str .. single_quote
        end
        str = str .. single_quote
        local RawItems = split_string(str, single_quote)
        local Items = { }
        for _, item in ipairs(RawItems) do
          local quoted_item
          if (item == empty) then
            quoted_item = empty
          else
            quoted_item = quote(item)
          end
          add_to_list(Items, quoted_item)
        end
        return list_to_str(Items, backslash .. single_quote)
      end
    return quote
  end
package.preload['workshop.concepts.shell.quote.SpaceChars'] =
  function(...)
    local SpaceChars
    do
      local Ascii = request('!.concepts.Ascii.Chars')
      SpaceChars = { Ascii.tab, Ascii.space, Ascii.newline }
    end
    return SpaceChars
  end
package.preload['workshop.concepts.shell.quote.SpecialChars'] =
  function(...)
    local SpecialChars
    do
      local Ascii = request('!.concepts.Ascii.Chars')
      local SpaceChars = request('SpaceChars')
      local add_list = request('!.concepts.list.add_list')
      SpecialChars =
        {
          Ascii.single_quote,
          Ascii.double_quote,
          Ascii.bang,
          Ascii.dollar_sign,
          Ascii.ampersand,
          Ascii.asterisk,
          Ascii.semicolon,
          Ascii.backslash,
          Ascii.caret,
          Ascii.backtick,
          Ascii.pipe,
          Ascii.less_than,
          Ascii.greater_than,
          Ascii.opening_paren,
          Ascii.closing_paren,
          Ascii.opening_bracket,
          Ascii.closing_bracket,
          Ascii.opening_brace,
          Ascii.closing_brace,
        }
      add_list(SpecialChars, SpaceChars)
    end
    return SpecialChars
  end
package.preload['workshop.concepts.words.to_string'] =
  function(...)
    local list_to_string = request('!.concepts.list.to_string')
    return
      function(Words)
        return list_to_string(Words, ' ')
      end
  end
package.preload['workshop.convert.file_from_str'] =
  function(...)
    return request('!.file_system.file.create')
  end
package.preload['workshop.convert.file_to_str'] =
  function(...)
    return request('!.file_system.file.to_string')
  end
package.preload['workshop.convert.lines_from_str'] =
  function(...)
    local newline = request('!.concepts.Ascii.Chars').newline
    local split_string = request('!.string.split')
    return
      function(str)
        return split_string(str, newline)
      end
  end
package.preload['workshop.file_system.directory.create'] =
  function(...)
    local directory_exists = request('exists')
    local get_mkdir_command = request('!.mechs.cmdline.get_cmd_mkdir')
    return
      function(dir_name)
        assert_string(dir_name)
        if directory_exists(dir_name) then
          return true
        end
        get_mkdir_command(dir_name):Execute()
        if directory_exists(dir_name) then
          return true
        end
        return false
      end
  end
package.preload['workshop.file_system.directory.exists'] =
  function(...)
    local get_cmd_dir_exists =
      request('!.mechs.cmdline.get_cmd_dir_exists')
    return
      function(dir_name)
        return (get_cmd_dir_exists(dir_name):Execute())
      end
  end
package.preload['workshop.file_system.directory.get_directories_list'] =
  function(...)
    local get_cmd_listdirs = request('!.mechs.cmdline.get_cmd_listdirs')
    local get_command_output_lines =
      request('!.system.get_command_output_lines')
    local to_clean_filelist = request('to_clean_filelist')
    return
      function(base_dir)
        return
          to_clean_filelist(
            get_command_output_lines(get_cmd_listdirs(base_dir)),
            base_dir
          )
      end
  end
package.preload['workshop.file_system.directory.get_files_list'] =
  function(...)
    local get_cmd_listfiles =
      request('!.mechs.cmdline.get_cmd_listfiles')
    local get_command_output_lines =
      request('!.system.get_command_output_lines')
    local to_clean_filelist = request('to_clean_filelist')
    return
      function(base_dir)
        return
          to_clean_filelist(
            get_command_output_lines(get_cmd_listfiles(base_dir)),
            base_dir
          )
      end
  end
package.preload['workshop.file_system.directory.get_total_files_list'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local retrieve
    do
      local get_files = request('get_files_list')
      local get_dirs = request('get_directories_list')
      local add_separator =
        request('!.concepts.path_name.add_separator')
      local add_to_list = request('!.concepts.list.add_item')
      retrieve =
        function(base_dir, Result)
          base_dir = add_separator(base_dir)
          local Files = get_files(base_dir)
          for _, file_name in ipairs(Files) do
            add_to_list(Result, normalize(base_dir .. file_name))
          end
          local Dirs = get_dirs(base_dir)
          for _, dir_name in ipairs(Dirs) do
            retrieve(normalize(base_dir .. dir_name), Result)
          end
        end
    end
    return
      function(base_dir)
        local Result = { }
        retrieve(normalize(base_dir), Result)
        return Result
      end
  end
package.preload['workshop.file_system.directory.to_clean_filelist'] =
  function(...)
    local add_separator = request('!.concepts.path_name.add_separator')
    local remove_prefix = request('!.string.remove_prefix')
    local add_to_list = request('!.concepts.list.add_item')
    local sort = table.sort
    return
      function(PathNames, base_dir)
        base_dir = add_separator(base_dir)
        local Result = { }
        for idx, file_name in ipairs(PathNames) do
          local cleaned_file_name = remove_prefix(file_name, base_dir)
          if (cleaned_file_name ~= '') then
            add_to_list(Result, cleaned_file_name)
          end
        end
        sort(Result)
        return Result
      end
  end
package.preload['workshop.file_system.file.close'] =
  function(...)
    local io_type = io.type
    return
      function(File)
        local file_type = io_type(File)
        if not is_string(file_type) then
          return
        end
        if (file_type == 'closed file') then
          return
        end
        File:close()
      end
  end
package.preload['workshop.file_system.file.create'] =
  function(...)
    local get_dir_name =
      request('!.concepts.path_name.get_host_dir_str')
    local mkdir = request('!.file_system.directory.create')
    local open_file = request('open')
    local close_file = request('close')
    return
      function(pathname, contents)
        assert_string(pathname)
        assert_string(contents)
        mkdir(get_dir_name(pathname))
        local File = open_file(pathname, 'wb')
        File:write(contents)
        close_file(File)
      end
  end
package.preload['workshop.file_system.file.open'] =
  function(...)
    local default_mode = 'rb'
    local io_open = io.open
    return
      function(pathname, mode)
        assert_string(pathname)
        mode = mode or default_mode
        local file, err_msg = io_open(pathname, mode)
        if not file then
          error(err_msg, 2)
        end
        return file
      end
  end
package.preload['workshop.file_system.file.open_for_reading'] =
  function(...)
    local open_file = request('open')
    return
      function(pathname)
        return open_file(pathname, 'rb')
      end
  end
package.preload['workshop.file_system.file.open_for_writing'] =
  function(...)
    local open_file = request('open')
    return
      function(pathname)
        return open_file(pathname, 'w+b')
      end
  end
package.preload['workshop.file_system.file.to_string'] =
  function(...)
    local open_file = request('open')
    local close_file = request('close')
    return
      function(pathname)
        local File = open_file(pathname, 'rb')
        local result = File:read('a')
        close_file(File)
        return result
      end
  end
package.preload['workshop.lua.regexp.magic_char_pattern'] =
  function(...)
    local magic_chars = request('magic_chars')
    local magic_char_patttern =
      '[' .. magic_chars:gsub('.', '%%%0') .. ']'
    return magic_char_patttern
  end
package.preload['workshop.lua.regexp.magic_chars'] =
  function(...)
    return '^$()[]%.?*+-'
  end
package.preload['workshop.lua.regexp.quote'] =
  function(...)
    local magic_char_pattern = request('magic_char_pattern')
    return
      function(s)
        return s:gsub(magic_char_pattern, '%%%0')
      end
  end
package.preload['workshop.mechs.cmdline.get_cmd_dir_exists'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local ShellCommand = request('!.concepts.ShellCommand')
    return
      function(pathname)
        local Command = { 'test', { '-d', normalize(pathname) } }
        return ShellCommand.create(Command)
      end
  end
package.preload['workshop.mechs.cmdline.get_cmd_listdirs'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local ShellCommand = request('!.concepts.ShellCommand')
    return
      function(dir_name)
        local Command =
          {
            'find',
            {
              normalize(dir_name),
              '-mindepth',
              '1',
              '-maxdepth',
              '1',
              '-type',
              'd',
            },
          }
        return ShellCommand.create(Command)
      end
  end
package.preload['workshop.mechs.cmdline.get_cmd_listfiles'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local ShellCommand = request('!.concepts.ShellCommand')
    return
      function(dir_name)
        local Command =
          {
            'find',
            { normalize(dir_name), '-maxdepth', '1', '-type', 'f' },
          }
        return ShellCommand.create(Command)
      end
  end
package.preload['workshop.mechs.cmdline.get_cmd_mkdir'] =
  function(...)
    local normalize = request('!.concepts.path_name.normalize')
    local ShellCommand = request('!.concepts.ShellCommand')
    return
      function(dir_name)
        local Command = { 'mkdir', { '-p', normalize(dir_name) } }
        return ShellCommand.create(Command)
      end
  end
package.preload['workshop.number.is_natural'] =
  function(...)
    return
      function(Number)
        assert_number(Number)
        if not is_integer(Number) then
          return false
        end
        if (Number <= 0) then
          return false
        end
        return true
      end
  end
package.preload['workshop.string.ends_with'] =
  function(...)
    local str_sub = string.sub
    return
      function(base_str, postfix_str)
        return (str_sub(base_str, -#postfix_str, -1) == postfix_str)
      end
  end
package.preload['workshop.string.remove_prefix'] =
  function(...)
    local starts_with = request('starts_with')
    local str_sub = string.sub
    return
      function(base_str, prefix_str)
        if not starts_with(base_str, prefix_str) then
          return base_str
        end
        return str_sub(base_str, #prefix_str + 1)
      end
  end
package.preload['workshop.string.split'] =
  function(...)
    local ends_with = request('!.string.ends_with')
    local quote_regexp = request('!.lua.regexp.quote')
    local str_find = string.find
    local add_to_list = request('!.concepts.list.add_item')
    return
      function(str, delimiter)
        assert_string(str)
        assert_string(delimiter)
        if (delimiter == '') then
          return { str }
        end
        if not ends_with(str, delimiter) then
          str = str .. delimiter
        end
        local Result = { }
        local item_capture = '(.-)' .. quote_regexp(delimiter) .. '()'
        local start_pos
        local end_pos
        local item_str
        start_pos = 1
        while true do
          start_pos, end_pos, item_str =
            str_find(str, item_capture, start_pos)
          if not start_pos then
            break
          end
          add_to_list(Result, item_str)
          start_pos = end_pos + 1
        end
        return Result
      end
  end
package.preload['workshop.string.starts_with'] =
  function(...)
    local str_sub = string.sub
    return
      function(base_str, prefix_str)
        return (str_sub(base_str, 1, #prefix_str) == prefix_str)
      end
  end
package.preload['workshop.system.get_command_output_lines'] =
  function(...)
    local lines_from_str = request('!.convert.lines_from_str')
    local get_command_output_lines =
      function(Command)
        local is_ok, ExecResult = Command:Execute()
        return lines_from_str(ExecResult.output)
      end
    return get_command_output_lines
  end
package.preload['workshop.system.install_assert_functions'] =
  function(...)
    local spawn_assert_func
    do
      local str_format = string.format
      spawn_assert_func =
        function(type_name)
          local checker = _G['is_' .. type_name]
          assert(checker)
          return
            function(val)
              if not checker(val) then
                local err_msg =
                  str_format('assert_%s(%s)', type_name, tostring(val))
                error(err_msg)
              end
            end
        end
    end
    local TypeNames = request('!.concepts.lua.TypeNames')
    local NumberTypeNames = request('!.concepts.lua.NumberTypeNames')
    local install_assert_funcs =
      function()
        for _, type_name in ipairs(TypeNames) do
          _G['assert_' .. type_name] = spawn_assert_func(type_name)
        end
        for _, number_type_name in ipairs(NumberTypeNames) do
          _G['assert_' .. number_type_name] =
            spawn_assert_func(number_type_name)
        end
      end
    return install_assert_funcs
  end
package.preload['workshop.system.install_is_functions'] =
  function(...)
    local type_is =
      function(type_name)
        return
          function(val)
            return (type(val) == type_name)
          end
      end
    local number_is
    do
      local math_type = math.type
      number_is =
        function(type_name)
          return
            function(val)
              if not is_number(val) then
                return false
              end
              return (math_type(val) == type_name)
            end
        end
    end
    local TypeNames = request('!.concepts.lua.TypeNames')
    local NumberTypeNames = request('!.concepts.lua.NumberTypeNames')
    return
      function()
        for _, type_name in ipairs(TypeNames) do
          _G['is_' .. type_name] = type_is(type_name)
        end
        for _, number_type_name in ipairs(NumberTypeNames) do
          _G['is_' .. number_type_name] = number_is(number_type_name)
        end
      end
  end
package.preload['workshop.table.apply_table'] =
  function(...)
    local keep_str = 'keep'
    local replace_str = 'replace'
    local remove_str = 'remove'
    local get_action =
      function(has_a, has_b, Rules)
        for _, Rule in ipairs(Rules) do
          if (Rule.has_a == has_a) and (Rule.has_b == has_b) then
            return Rule.action
          end
        end
        return keep_str
      end
    local apply_table
    apply_table =
      function(A, B, Rules)
        local Keys = { }
        do
          for a_key in pairs(A) do
            Keys[a_key] = true
          end
          for b_key in pairs(B) do
            Keys[b_key] = true
          end
        end
        for key in pairs(Keys) do
          local a_key = A[key]
          local b_key = B[key]
          if is_table(a_key) and is_table(b_key) then
            apply_table(a_key, b_key, Rules)
          else
            local has_a = not is_nil(a_key)
            local has_b = not is_nil(b_key)
            local action = get_action(has_a, has_b, Rules)
            if (action == keep_str) then
              ;
            elseif (action == replace_str) then
              A[key] = B[key]
            elseif (action == remove_str) then
              A[key] = nil
            end
          end
        end
      end
    local check_rule =
      function(Rule)
        local has_a = is_boolean(Rule.has_a)
        local has_b = is_boolean(Rule.has_b)
        local action = Rule.action
        local is_known_action =
          (action == keep_str) or
          (action == replace_str) or
          (action == remove_str)
        return has_a and has_b and is_known_action
      end
    return
      function(A, B, Rules)
        assert_table(A)
        assert_table(B)
        assert_table(Rules)
        assert(A ~= B)
        for index, Rule in ipairs(Rules) do
          if not check_rule(Rule) then
            error('Unsupported rule.')
          end
        end
        apply_table(A, B, Rules)
      end
  end
package.preload['workshop.table.attach_methods'] =
  function(...)
    return
      function(Object, Methods)
        assert_table(Object)
        assert_table(Methods)
        local Metatable =
          {
            __index = Methods,
            __newindex =
              function()
                error('Table is locked for additions/removals.')
              end,
          }
        setmetatable(Object, Metatable)
      end
  end
package.preload['workshop.table.clone'] =
  function(...)
    return
      function(Node)
        local clone
        do
          local Cloned = { }
          clone =
            function(Node)
              if (type(Node) ~= 'table') then
                return Node
              end
              if Cloned[Node] then
                return Cloned[Node]
              end
              local Result = { }
              Cloned[Node] = Result
              for key, value in pairs(Node) do
                Result[clone(key)] = clone(value)
              end
              setmetatable(Result, getmetatable(Node))
              return Result
            end
        end
        return clone(Node)
      end
  end
package.preload['workshop.table.create_instance'] =
  function(...)
    local clone = request('clone')
    local attach_methods = request('attach_methods')
    return
      function(Data, Methods)
        assert_table(Data)
        assert_table(Methods)
        local Result
        Result = clone(Data)
        attach_methods(Result, Methods)
        return Result
      end
  end
package.preload['workshop.table.get_values'] =
  function(...)
    local add_to_list = request('!.concepts.list.add_item')
    return
      function(List)
        assert_table(List)
        local Values = { }
        for _, value in pairs(List) do
          add_to_list(Values, value)
        end
        return Values
      end
  end
package.preload['workshop.table.map_values'] =
  function(...)
    return
      function(List)
        assert_table(List)
        local Result = { }
        for _, value in pairs(List) do
          Result[value] = true
        end
        return Result
      end
  end
package.preload['workshop.table.new'] =
  function(...)
    local clone = request('clone')
    local patch = request('patch')
    return
      function(Base, Overrides)
        assert_table(Base)
        local Result = clone(Base)
        if is_table(Overrides) then
          patch(Result, Overrides)
        end
        return Result
      end
  end
package.preload['workshop.table.patch'] =
  function(...)
    local Rules = { { has_a = true, has_b = true, action = 'replace' } }
    local apply_table = request('apply_table')
    return
      function(Result, Additions)
        apply_table(Result, Additions, Rules)
      end
  end
return require('files_tree')